/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.withlove.view;

import com.withlove.DAO.PatientDAOImpl;
import com.withlove.model.Patient;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author SENA
 */
public class crud extends javax.swing.JPanel {
    
    PatientDAOImpl patient = new PatientDAOImpl();
    
    public crud() {
        initComponents();
        loadDataIntoTable();
        adjustColumnSizes();
    }
    
    private void loadDataIntoTable() {
        // Suponiendo que tienes una instancia de PatientDAOImpl llamada patientDAOImpl
        List<Patient> patients = patient.getAll();

        // Preparamos los datos para la tabla
        Object[][] data = new Object[patients.size()][9]; // 9 es el número de columnas que tienes en tu tabla
        String[] columnNames = {"ID", "Nombre", "Apellido", "Aseguradora"};

        for (int i = 0; i < patients.size(); i++) {
           /* Patient patient = patients.get(i);
            data[i][0] = patient.getIdPatient();
            data[i][1] = patient.getIdentification();
            data[i][2] = patient.getNamePatient();
            data[i][3] = patient.getLastNamePa();
            data[i][4] = patient.getEmail();
            data[i][5] = patient.getPhoneNumberPatient();
            data[i][6] = patient.getBirthdayDate();
            data[i][7] = patient.getGender() == 1 ? "Masculino" : "Femenino"; // Ejemplo de conversión de género
            data[i][8] = patient.getInsurer(); */
          Patient patient = patients.get(i);
            data[i][0] = patient.getIdPatient();            
            data[i][1] = patient.getNamePatient();
            data[i][2] = patient.getLastNamePa();
            data[i][3] = patient.getInsurer(); 
          
        }

        // Configuramos el modelo de la JTable
        tablePatients.setModel(new DefaultTableModel(data, columnNames));
        
        adjustColumnSizes();
    }
    
        private void adjustColumnSizes() {
        // Ajustamos el tamaño de las columnas
        TableColumn column;
        for (int i = 0; i < tablePatients.getColumnCount(); i++) {
            column = tablePatients.getColumnModel().getColumn(i);
            if (i == 0) {
                column.setPreferredWidth(20); // ID
            } else if (i == 1) {
                column.setPreferredWidth(40); // Identificación
            } else if (i == 2 || i == 3) {
                column.setPreferredWidth(60); // Nombre y Apellido
            } else if (i == 4) {
                column.setPreferredWidth(70); // Email
            } else if (i == 5) {
                column.setPreferredWidth(40); // Teléfono
            } else if (i == 6) {
                column.setPreferredWidth(50); // Fecha de Nacimiento
            } else if (i == 7) {
                column.setPreferredWidth(40); // Género
            } else if (i == 8) {
                column.setPreferredWidth(50); // Aseguradora
            }
        }
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablePatients = new javax.swing.JTable();

        setMinimumSize(new java.awt.Dimension(1000, 540));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablePatients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IdPatient", "Name", "LastName", "Insurer"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablePatients);
        if (tablePatients.getColumnModel().getColumnCount() > 0) {
            tablePatients.getColumnModel().getColumn(0).setMinWidth(60);
            tablePatients.getColumnModel().getColumn(0).setPreferredWidth(60);
            tablePatients.getColumnModel().getColumn(0).setMaxWidth(60);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 880, 250));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablePatients;
    // End of variables declaration//GEN-END:variables
}
