/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.withlove.view;

import java.awt.Color;
import static java.awt.Color.black;
import static java.awt.Color.white;
import java.awt.Cursor;

/**
 *
 * @author USER
 */
public class IntMainProfessional extends javax.swing.JPanel {

    /**
     * Creates new form homeU
     */
    public IntMainProfessional() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnAppointment = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Health professionals at your door");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 310, 50));

        jLabel3.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Personalized attention in your home");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 320, 50));

        jTextArea2.setBackground(new java.awt.Color(0, 204, 255));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Roboto", 3, 12)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea2.setRows(5);
        jTextArea2.setText("Lorem ipsum dolor sit amet consectetur adipisicing elit. \nEarum odio est facere, molestiae aspernatur vel vero inventore\n ex, nulla magnam illum fugiat perferendis amet laborum non\n qui eaque. Laboriosam, neque? A officia quo blanditiis saepe\n hic, aut architecto nobis distinctio odio iure totam quibusdam\n asperiores incidu");
        jScrollPane2.setViewportView(jTextArea2);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 300, 350, 140));

        jTextArea3.setBackground(new java.awt.Color(0, 204, 255));
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Roboto", 3, 12)); // NOI18N
        jTextArea3.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea3.setRows(5);
        jTextArea3.setText("Lorem ipsum dolor sit amet consectetur adipisicing elit. \nEarum odio est facere, molestiae aspernatur vel vero inventore\n ex, nulla magnam illum fugiat perferendis amet laborum non\n qui eaque. Laboriosam, neque? A officia quo blanditiis saepe\n hic, aut architecto nobis distinctio odio iure totam quibusdam\n asperiores incidu");
        jScrollPane3.setViewportView(jTextArea3);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 350, 140));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 51));
        jLabel1.setText("VISION");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto Black", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 51));
        jLabel4.setText("MISSION");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 2, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("(Lo primero que se hará es buscar al professional)");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 300, -1));

        btnAppointment.setBackground(new java.awt.Color(255, 153, 153));
        btnAppointment.setFont(new java.awt.Font("Roboto Black", 3, 12)); // NOI18N
        btnAppointment.setText("Manage Appointments");
        btnAppointment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAppointmentMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAppointmentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAppointmentMouseExited(evt);
            }
        });
        add(btnAppointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 170, 40));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 2, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Para agendar tu cita en el siguiente boton");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 250, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/withlove/img/background.jpg"))); // NOI18N
        add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 540));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAppointmentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAppointmentMouseEntered
        // TODO add your handling code here:
        btnAppointment.setCursor(new Cursor(Cursor.HAND_CURSOR));
        int rgb = Integer.parseInt("00CCFF", 16);
        Color color = new Color(rgb);
        btnAppointment.setBackground(color);
        btnAppointment.setForeground(white);
    }//GEN-LAST:event_btnAppointmentMouseEntered

    private void btnAppointmentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAppointmentMouseExited
        // TODO add your handling code here:
         btnAppointment.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        int rgb = Integer.parseInt("FF9999", 16);
        Color color = new Color(rgb);
        btnAppointment.setBackground(color);
        btnAppointment.setForeground(black);
        
    }//GEN-LAST:event_btnAppointmentMouseExited

    private void btnAppointmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAppointmentMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnAppointmentMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnAppointment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    // End of variables declaration//GEN-END:variables
}
