/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.withlove.view;

import com.withlove.DAO.PatientDAOImpl;
import com.withlove.DAO.ProfessionalDAOImpl;
import com.withlove.DAO.patientDAO;
import com.withlove.DAO.professionalDAO;
import com.withlove.model.Patient;
import com.withlove.model.Professional;
import java.awt.Color;
import static java.awt.Color.black;
import static java.awt.Color.white;
import java.awt.Cursor;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class signUp extends javax.swing.JFrame {

    professionalDAO daoPro = new ProfessionalDAOImpl();
    patientDAO daoPat = new PatientDAOImpl();

    public int licenseN = 1;

    public signUp() {
        initComponents();
        setImageLabel(background, "src/com/withlove/img/background.jpg");
        this.txtProfession.setEnabled(false);
        this.tareaInformation.setEnabled(false);
    }

    private void setImageLabel(JLabel labelName, String root) {
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(labelName.getWidth(), labelName.getHeight(), Image.SCALE_DEFAULT));
        labelName.setIcon(icon);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        container = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jlabel16 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtInformation = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtIdentityC = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtNeighborhood = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtProfession = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        RbtnPatient = new javax.swing.JRadioButton();
        RbtnProfessional = new javax.swing.JRadioButton();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tareaInformation = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        btnSignUp = new javax.swing.JButton();
        cbShow1 = new javax.swing.JCheckBox();
        cbShow2 = new javax.swing.JCheckBox();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 204, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(350, 600));

        jLabel5.setFont(new java.awt.Font("Roboto Black", 0, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("WELCOME");

        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TO");

        jLabel6.setFont(new java.awt.Font("Roboto Black", 0, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("WITH");

        jLabel7.setFont(new java.awt.Font("Roboto Black", 0, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("LOVE");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel5)
                .addContainerGap(64, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addContainerGap(221, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        container.setPreferredSize(new java.awt.Dimension(650, 600));
        container.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Roboto Black", 0, 48)); // NOI18N
        jLabel3.setText("SIGN UP");
        container.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Roboto Black", 3, 14)); // NOI18N
        jLabel2.setText("Name:");
        container.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 195, 80, -1));

        jLabel8.setFont(new java.awt.Font("Roboto Black", 3, 14)); // NOI18N
        jLabel8.setText("Last name:");
        container.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 225, 90, -1));

        jLabel9.setFont(new java.awt.Font("Roboto Black", 3, 14)); // NOI18N
        jLabel9.setText("neighborhood:");
        container.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 255, 100, -1));

        jLabel10.setFont(new java.awt.Font("Roboto Black", 3, 14)); // NOI18N
        jLabel10.setText("Address:");
        container.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 285, 90, -1));

        jlabel16.setFont(new java.awt.Font("Roboto Black", 3, 14)); // NOI18N
        jlabel16.setText("Password:");
        container.add(jlabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 285, 120, -1));

        jLabel12.setFont(new java.awt.Font("Roboto Black", 3, 14)); // NOI18N
        jLabel12.setText("Email:");
        container.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 195, 60, -1));

        jLabel13.setFont(new java.awt.Font("Roboto Black", 3, 14)); // NOI18N
        jLabel13.setText("Id card:");
        container.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 165, 100, -1));

        jLabel14.setFont(new java.awt.Font("Roboto Black", 3, 14)); // NOI18N
        jLabel14.setText("Profession:");
        container.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 315, 120, -1));

        jLabel15.setFont(new java.awt.Font("Roboto Black", 3, 14)); // NOI18N
        jLabel15.setText("city:");
        container.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 165, 110, -1));

        txtInformation.setFont(new java.awt.Font("Roboto Black", 3, 14)); // NOI18N
        txtInformation.setText("Information:");
        container.add(txtInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 90, -1));

        jLabel17.setFont(new java.awt.Font("Roboto Black", 3, 14)); // NOI18N
        jLabel17.setText(" Phone number:");
        container.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 225, 110, -1));
        container.add(txtIdentityC, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 170, -1));
        container.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 170, -1));
        container.add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 170, -1));
        container.add(txtNeighborhood, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 170, -1));
        container.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 170, -1));
        container.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 170, -1));
        container.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 170, -1));

        txtProfession.setEditable(false);
        container.add(txtProfession, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, 170, -1));
        container.add(txtCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 170, -1));

        buttonGroup1.add(RbtnPatient);
        RbtnPatient.setSelected(true);
        RbtnPatient.setText("Patient");
        RbtnPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbtnPatientActionPerformed(evt);
            }
        });
        container.add(RbtnPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, -1, -1));

        buttonGroup1.add(RbtnProfessional);
        RbtnProfessional.setText("Professional");
        RbtnProfessional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbtnProfessionalActionPerformed(evt);
            }
        });
        container.add(RbtnProfessional, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, -1, -1));

        btnBack.setBackground(new java.awt.Color(255, 153, 153));
        btnBack.setFont(new java.awt.Font("Roboto", 3, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(0, 0, 0));
        btnBack.setText("BACK");
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackMouseExited(evt);
            }
        });
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        container.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 470, 120, 30));

        tareaInformation.setEditable(false);
        tareaInformation.setColumns(20);
        tareaInformation.setRows(5);
        jScrollPane1.setViewportView(tareaInformation);

        container.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 363, 490, 70));

        jLabel16.setFont(new java.awt.Font("Roboto Black", 3, 14)); // NOI18N
        jLabel16.setText("Password:");
        container.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 255, 120, -1));
        container.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 170, -1));
        container.add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, 170, -1));

        btnSignUp.setBackground(new java.awt.Color(255, 153, 153));
        btnSignUp.setFont(new java.awt.Font("Roboto", 3, 14)); // NOI18N
        btnSignUp.setForeground(new java.awt.Color(0, 0, 0));
        btnSignUp.setText("SIGN UP");
        btnSignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSignUpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSignUpMouseExited(evt);
            }
        });
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });
        container.add(btnSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, 120, 30));

        cbShow1.setBackground(new java.awt.Color(255, 204, 204));
        cbShow1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbShow1ActionPerformed(evt);
            }
        });
        container.add(cbShow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, -1, -1));

        cbShow2.setBackground(new java.awt.Color(255, 204, 204));
        cbShow2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbShow2ActionPerformed(evt);
            }
        });
        container.add(cbShow2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 280, -1, -1));
        container.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 600));

        jPanel1.add(container, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 650, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RbtnPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbtnPatientActionPerformed
        // TODO add your handling code here:
        // btn Patient
        this.txtProfession.setText("");
        this.tareaInformation.setText("");
        this.txtProfession.setEnabled(false);
        this.tareaInformation.setEnabled(false);
    }//GEN-LAST:event_RbtnPatientActionPerformed

    private void RbtnProfessionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbtnProfessionalActionPerformed
        // TODO add your handling code here:
        // btn Professional
        this.txtProfession.setText("");
        this.tareaInformation.setText("");
        this.txtProfession.setEnabled(true);
        this.tareaInformation.setEnabled(true);
        this.txtProfession.setEditable(true);
        this.tareaInformation.setEditable(true);
    }//GEN-LAST:event_RbtnProfessionalActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        // Btn Back
        login log = new login();
        log.setVisible(true);
        log.setLocationRelativeTo(null);
        log.setResizable(false);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        // TODO add your handling code here:
        // Btn Sign Up
        if (RbtnPatient.isSelected()) {
            if (!txtIdentityC.getText().trim().equals("") && !txtName.getText().trim().equals("") && !txtLastName.getText().trim().equals("") && !txtNeighborhood.getText().trim().equals("")
                    && !txtAddress.getText().trim().equals("") && !txtCity.getText().trim().equals("") && !txtEmail.getText().trim().equals("") && !txtPhone.getText().trim().equals("")
                    && !(new String(jPasswordField1.getPassword())).trim().equals("") && !(new String(jPasswordField2.getPassword())).trim().equals("")) {
                if (new String(jPasswordField1.getPassword()).equals(new String(jPasswordField2.getPassword()))) {
                    if (daoPat.validateEmail(txtEmail.getText().trim())) {
                        try {
                        //    String passwordE = daoPat.ecnode(new String(jPasswordField1.getPassword()));
                            // (Integer.parseInt(txtIdentityC.getText())), txtName.getText(), txtLastName.getText(), txtNeighborhood.getText(), txtAddress.getText(), txtCity.getText(), txtEmail.getText(), txtPhone.getText(), passwordE)
                          //  Patient pat = new Patient((Integer.parseInt(txtIdentityC.getText())), txtName.getText(), txtLastName.getText(), txtNeighborhood.getText(), txtAddress.getText(), txtCity.getText(), txtEmail.getText(), txtPhone.getText(), passwordE);
                         //   daoPat.create(pat);
                            JOptionPane.showConfirmDialog(null, "Patient Created");
                            login log = new login();
                            log.setVisible(true);
                            log.setLocationRelativeTo(null);
                            log.setResizable(false);
                            this.setVisible(false);
                        } catch (Exception e) {
                            JOptionPane.showConfirmDialog(null, "You misspelled in the ID field");
                        }
                    } else{
                        JOptionPane.showConfirmDialog(null, "The email is misspelled");
                    }

                } else {
                    JOptionPane.showConfirmDialog(null, "Passwords are not the same");
                }
            } else {
                JOptionPane.showConfirmDialog(null, "Please fill in all fields. Some fields are still empty.");
            }
        }
        if (RbtnProfessional.isSelected()) {
            if (!txtIdentityC.getText().trim().equals("") && !txtName.getText().trim().equals("") && !txtLastName.getText().trim().equals("") && !txtNeighborhood.getText().trim().equals("")
                    && !txtAddress.getText().trim().equals("") && !txtCity.getText().trim().equals("") && !txtEmail.getText().trim().equals("") && !txtPhone.getText().trim().equals("")
                    && !(new String(jPasswordField1.getPassword()).trim().equals("")) && !(new String(jPasswordField2.getPassword()).trim().equals("")) && !txtProfession.getText().trim().equals("") && !txtInformation.getText().trim().equals("")) {
                if (new String(jPasswordField1.getPassword()).equals(new String(jPasswordField2.getPassword()))) {
                    if (daoPro.validateEmail(txtEmail.getText().trim())) {
                        try {
                          //  String passwordE = daoPro.ecnode(new String(jPasswordField1.getPassword()));
                            // (Integer.parseInt(txtIdentityC.getText())), txtName.getText(), txtLastName.getText(), txtNeighborhood.getText(), txtAddress.getText(), txtCity.getText(), txtEmail.getText(), txtPhone.getText(), passwordE, txtProfession.getText(), txtInformation.getText())
                         //   Professional pro = new Professional((Integer.parseInt(txtIdentityC.getText())), txtName.getText(), txtLastName.getText(), txtNeighborhood.getText(), txtAddress.getText(), txtCity.getText(), txtEmail.getText(), txtPhone.getText(), passwordE, txtProfession.getText(), txtInformation.getText());
                      //      daoPro.create(pro);;
                            JOptionPane.showConfirmDialog(null, "Professional Created");
                            login log = new login();
                            log.setVisible(true);
                            log.setLocationRelativeTo(null);
                            log.setResizable(false);
                            this.setVisible(false);
                        } catch (Exception e) {
                            JOptionPane.showConfirmDialog(null, "You misspelled in the ID field");
                        }
                    } else {
                        JOptionPane.showConfirmDialog(null, "The email is misspelled");
                    }

                } else {
                    JOptionPane.showConfirmDialog(null, "Passwords are not the same");
                }
            } else {
                JOptionPane.showConfirmDialog(null, "Please fill in all fields. Some fields are still empty.");
            }
        }

        // *****************************************************************************************************************************************************

    }//GEN-LAST:event_btnSignUpActionPerformed

    private void btnSignUpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignUpMouseEntered
        // TODO add your handling code here:
        // mouse entrando
        btnSignUp.setCursor(new Cursor(Cursor.HAND_CURSOR));
        int rgb = Integer.parseInt("00CCFF", 16);
        Color color = new Color(rgb);
        btnSignUp.setBackground(color);
        btnSignUp.setForeground(white);
    }//GEN-LAST:event_btnSignUpMouseEntered

    private void btnSignUpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignUpMouseExited
        // TODO add your handling code here:
        btnSignUp.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        int rgb = Integer.parseInt("FF9999", 16);
        Color color = new Color(rgb);
        btnSignUp.setBackground(color);
        btnSignUp.setForeground(black);
    }//GEN-LAST:event_btnSignUpMouseExited

    private void btnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseEntered
        // TODO add your handling code here:
        btnBack.setCursor(new Cursor(Cursor.HAND_CURSOR));
        int rgb = Integer.parseInt("00CCFF", 16);
        Color color = new Color(rgb);
        btnBack.setBackground(color);
        btnBack.setForeground(white);
    }//GEN-LAST:event_btnBackMouseEntered

    private void btnBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseExited
        // TODO add your handling code here:
        btnBack.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        int rgb = Integer.parseInt("FF9999", 16);
        Color color = new Color(rgb);
        btnBack.setBackground(color);
        btnBack.setForeground(black);
    }//GEN-LAST:event_btnBackMouseExited

    private void cbShow1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbShow1ActionPerformed
        // TODO add your handling code here:
        if (cbShow1.isSelected()) {
            jPasswordField1.setEchoChar((char) 0); //password = JPasswordField
        } else {
            jPasswordField1.setEchoChar('*');
        }
    }//GEN-LAST:event_cbShow1ActionPerformed

    private void cbShow2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbShow2ActionPerformed
        // TODO add your handling code here:
        if (cbShow2.isSelected()) {
            jPasswordField2.setEchoChar((char) 0); //password = JPasswordField
        } else {
            jPasswordField2.setEchoChar('*');
        }
    }//GEN-LAST:event_cbShow2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RbtnPatient;
    private javax.swing.JRadioButton RbtnProfessional;
    private javax.swing.JLabel background;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSignUp;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cbShow1;
    private javax.swing.JCheckBox cbShow2;
    private javax.swing.JPanel container;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlabel16;
    private javax.swing.JTextArea tareaInformation;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtIdentityC;
    private javax.swing.JLabel txtInformation;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNeighborhood;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtProfession;
    // End of variables declaration//GEN-END:variables
}
