/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.withlove.view;

import com.withlove.DAO.AppointmentDAOImpl;
import com.withlove.DAO.CategoryDAOImpl;
import com.withlove.DAO.PatientDAOImpl;
import com.withlove.DAO.ProfessionalDAOImpl;
import com.withlove.model.Appointment;
import com.withlove.model.Patient;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author SENA
 */
public class tableAppointment extends javax.swing.JPanel {
    
     PatientDAOImpl patientDAO = new PatientDAOImpl();
     ProfessionalDAOImpl professionalDAO = new ProfessionalDAOImpl();
     CategoryDAOImpl categoryDAO = new CategoryDAOImpl();
     AppointmentDAOImpl appointmentDAO = new AppointmentDAOImpl();
    
    public tableAppointment() {
        initComponents();
        loadDataIntoTable();
       // adjustColumnSizes();
        this.txtCountPatient.setText("Patient: "+patientDAO.countPatient());
        this.txtCountProfessional.setText("Professional: "+professionalDAO.countProfessional());
        this.txtCountCategory.setText("Category: "+categoryDAO.countCategory());
        
    }
    
    private void loadDataIntoTable() {
        // Suponiendo que tienes una instancia de PatientDAOImpl llamada patientDAOImpl
        List<Appointment> appointmentss = appointmentDAO.getAll();

        // Preparamos los datos para la tabla
        Object[][] data = new Object[appointmentss.size()][5]; // 9 es el número de columnas que tienes en tu tabla
        String[] columnNames = {"ID", "IdProfessional", "IdPatient", "Date","Hour"};

        for (int i = 0; i < appointmentss.size(); i++) {
           
          Appointment appoint = appointmentss.get(i);
            data[i][0] = appoint.getIdAppointment();
            data[i][1] = appoint.getIdProfessional();
            data[i][2] = appoint.getIdentification();
            data[i][3] = appoint.getDateAvailable();
            data[i][4] = appoint.getHourAvailable();
            
          
        }

        // Configuramos el modelo de la JTable
        tablePatients.setModel(new DefaultTableModel(data, columnNames));
        
       // adjustColumnSizes();
    }
    /*
        private void adjustColumnSizes() {
        // Ajustamos el tamaño de las columnas
        TableColumn column;
        for (int i = 0; i < tablePatients.getColumnCount(); i++) {
            column = tablePatients.getColumnModel().getColumn(i);
            if (i == 0) {
                column.setPreferredWidth(20); // ID
            } else if (i == 1) {
                column.setPreferredWidth(40); // Identificación
            } else if (i == 2 || i == 3) {
                column.setPreferredWidth(60); // Nombre y Apellido
            } else if (i == 4) {
                column.setPreferredWidth(70); // Email
            } else if (i == 5) {
                column.setPreferredWidth(40); // Teléfono
            } else if (i == 6) {
                column.setPreferredWidth(50); // Fecha de Nacimiento
            } else if (i == 7) {
                column.setPreferredWidth(40); // Género
            } else if (i == 8) {
                column.setPreferredWidth(50); // Aseguradora
            }
        }
    }
*/
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablePatients = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtCountProfessional = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtCountPatient = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txtCountCategory = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(760, 540));
        setPreferredSize(new java.awt.Dimension(760, 540));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablePatients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IdPatient", "Name", "LastName", "Insurer"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablePatients);
        if (tablePatients.getColumnModel().getColumnCount() > 0) {
            tablePatients.getColumnModel().getColumn(0).setMinWidth(60);
            tablePatients.getColumnModel().getColumn(0).setPreferredWidth(60);
            tablePatients.getColumnModel().getColumn(0).setMaxWidth(60);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 590, 250));

        jButton1.setText("Create");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, -1));

        jButton2.setText("Delete");
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, -1, -1));

        jButton3.setText("Update");
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, -1, -1));

        txtCountProfessional.setText("No borrar esto");
        add(txtCountProfessional, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 90, 70));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCountPatient.setText("No borrar esto");
        jPanel1.add(txtCountPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 80, 70));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 120, 90));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 120, 90));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCountCategory.setText("No borrar esto");
        jPanel3.add(txtCountCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 70));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 120, 90));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablePatients;
    private javax.swing.JLabel txtCountCategory;
    private javax.swing.JLabel txtCountPatient;
    private javax.swing.JLabel txtCountProfessional;
    // End of variables declaration//GEN-END:variables
}
